Repository readmeio/oas, pull requests merged in 2020-10, with the labels that each got.

#282 Feature(findOperationWithoutMethod): Expose function for resolving URI without method
  packages/tooling/__tests__/oas.test.js
  packages/tooling/src/oas.js
Labels: type:enhancement

#283 docs: improving our oas petstore example to pair it with the swagger version
  packages/examples/3.0/json/petstore.json
  packages/examples/3.0/yaml/petstore.yaml
  packages/tooling/__tests__/__fixtures__/petstore.json
  packages/tooling/__tests__/lib/find-schema-definition.test.js
  packages/tooling/__tests__/lib/flatten-schema.test.js
  packages/tooling/__tests__/lib/get-path.test.js
  packages/tooling/__tests__/oas.test.js
  packages/tooling/__tests__/operation.test.js
Labels: type:enhancement

#288 fix: flattenSchema not properly flattening allOf/oneOf/anyOf schemas
  packages/tooling/__tests__/__fixtures__/nested-allof-flattening.json
  packages/tooling/__tests__/lib/flatten-schema.test.js
  packages/tooling/src/lib/flatten-schema.js
Labels: type:bug

#292 fix: swapping out the $ref parsing engine of flattenSchema
  __tests__/tooling/lib/flatten-schema.test.js
  package-lock.json
  package.json
  tooling/lib/flatten-schema.js
Labels: scope:dependency, type:bug, type:refactor
