Repository readmeio/oas, pull requests merged in 2021-04, with the labels that each got.

#406 refactor: extract part of prepareSecurity() function into a new function
  __tests__/tooling/operation.test.js
  tooling/operation.js
Labels: type:refactor

#407 Adds the ability to extract response data similar to getParametersAsJsonSchema
  __tests__/tooling/operation.test.js
  __tests__/tooling/operation/get-response-as-json-schema.test.js
  tooling/operation.js
  tooling/operation/get-response-as-json-schema.js
Labels: type:enhancement

#410 feat: adding support retrieving 204/empty responses
  __tests__/tooling/__datasets__/operation-examples.json
  __tests__/tooling/operation/get-response-examples.test.js
  tooling/operation/get-response-examples.js
Labels: type:enhancement

#411 fix: adding support for matching schemeless OAS server urls
  __tests__/tooling/index.test.js
  tooling/index.js
Labels: type:bug
