Repository readmeio/oas, pull requests merged in 2022-01, with the labels that each got.

#563 fix: improved support for common params
  __tests__/__datasets__/parameters-common.json
  __tests__/operation.test.ts
  src/index.ts
  src/operation.ts
  src/utils.ts
Labels: bug, enhancement

#575 fix: callbacks not having path-level data to retrieve common summaries
  __tests__/__datasets__/callbacks.json
  __tests__/operation.test.ts
  src/operation.ts
Labels: bug

#576 fix(operation): support operations without responses
  __tests__/__datasets__/3-1-no-responses.json
  __tests__/operation.test.ts
  src/operation.ts
Labels: bug

#577 chore: make our jsdoc eslint rules a bit less obnoxious
  .eslintrc
  __tests__/__fixtures__/json-schema.ts
  __tests__/__fixtures__/json-stringify-clean.js
  __tests__/lib/openapi-to-json-schema.test.ts
  __tests__/operation/get-parameters-as-json-schema.test.js
  package-lock.json
  package.json
  src/index.ts
  src/lib/find-schema-definition.ts
  src/lib/get-auth.ts
  src/lib/get-mediatype-examples.ts
  src/lib/get-schema.ts
  src/lib/get-user-variable.ts
  src/lib/matches-mimetype.ts
  src/lib/openapi-to-json-schema.ts
  src/operation.ts
  src/operation/get-callback-examples.ts
  src/operation/get-parameters-as-json-schema.ts
  src/operation/get-requestbody-examples.ts
  src/operation/get-response-as-json-schema.ts
  src/operation/get-response-examples.ts
  src/samples/utils.ts
Labels: documentation

#579 fix: refactoring allOf schemas to be pre-merged when we generate JSON Schema
  .eslintrc
  __tests__/__datasets__/parameters-common.json
  __tests__/__datasets__/polymorphism-quirks.json
  __tests__/__datasets__/schema-deprecated.json
  __tests__/lib/__snapshots__/openapi-to-json-schema.test.ts.snap
  __tests__/lib/openapi-to-json-schema.test.ts
  __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.js.snap
  __tests__/operation/get-parameters-as-json-schema.test.js
  src/lib/openapi-to-json-schema.ts
  src/operation.ts
  src/operation/get-parameters-as-json-schema.ts
  src/rmoas.types.ts
Labels: bug, enhancement, refactor

#580 feat: addition of a getRequestBody accessor
  __tests__/operation.test.ts
  src/operation.ts
Labels: enhancement

#582 refactor: use default for samples over generic type
  __tests__/samples/index.test.ts
  src/samples/index.ts
Labels: enhancement, refactor

#581 refactor: cleaning up the messy `getSchema` library and other improvements
  __tests__/__datasets__/callbacks.json
  __tests__/__datasets__/petstore-nondereferenced.json
  __tests__/__snapshots__/operation.test.ts.snap
  __tests__/operation.test.ts
  src/lib/dedupe-common-parameters.ts
  src/lib/get-schema.ts
  src/operation.ts
  src/operation/get-parameters-as-json-schema.ts
Labels: enhancement, refactor

#585 fix: funky typing with how we extract examples during JSON Schema generation
  __tests__/lib/openapi-to-json-schema.test.ts
  __tests__/samples/index.test.ts
  src/lib/openapi-to-json-schema.ts
  src/operation/get-parameters-as-json-schema.ts
Labels: enhancement, refactor

#584 fix: show response headers w/o mediaType content
  __tests__/__datasets__/operation-examples.json
  __tests__/operation/get-response-examples.test.ts
  src/operation/get-response-examples.ts
Labels: bug

#587 fix: bumping oas-normalize to fix a bug with header content validation
  package-lock.json
  package.json
Labels: bug, dependencies
