Repository readmeio/oas, pull requests merged in 2023-10, with the labels that each got.

#812 refactor: build cleanup
  .github/workflows/ci.yml
  packages/oas-extensions/package.json
  packages/oas-normalize/package.json
  packages/oas-to-har/package.json
  packages/oas/package.json
Labels: refactor

#813 refactor: consolidating our ts and tsup configs
  package-lock.json
  package.json
  packages/oas-extensions/package.json
  packages/oas-extensions/tsconfig.json
  packages/oas-extensions/tsup.config.ts
  packages/oas-normalize/.eslintrc
  packages/oas-normalize/package.json
  packages/oas-normalize/src/.sink.d.ts
  packages/oas-normalize/tsconfig.json
  packages/oas-normalize/tsup.config.ts
  packages/oas-to-har/package.json
  packages/oas-to-har/tsconfig.json
  packages/oas-to-har/tsup.config.ts
  packages/oas/package.json
  packages/oas/src/lib/helpers.ts
  packages/oas/src/operation/get-response-as-json-schema.ts
  packages/oas/tsconfig.json
  packages/oas/tsup.config.ts
  tsconfig.base.json
  tsup.config.ts
Labels: refactor

#814 feat(esm): flipping on our ESM ESLint config in all packages
  .eslintrc
  packages/oas-extensions/.eslintrc
  packages/oas-extensions/test/index.test.ts
  packages/oas-extensions/tsup.config.ts
  packages/oas-normalize/.eslintrc
  packages/oas-normalize/src/index.ts
  packages/oas-normalize/test/index.test.ts
  packages/oas-normalize/tsup.config.ts
  packages/oas-to-har/.eslintrc
  packages/oas/.eslintrc
  packages/oas/src/analyzer/index.ts
  packages/oas/src/analyzer/queries/openapi.ts
  packages/oas/src/analyzer/queries/readme.ts
  packages/oas/src/index.ts
  packages/oas/src/lib/dedupe-common-parameters.ts
  packages/oas/src/lib/get-auth.ts
  packages/oas/src/lib/get-mediatype-examples.ts
  packages/oas/src/lib/get-user-variable.ts
  packages/oas/src/lib/helpers.ts
  packages/oas/src/lib/openapi-to-json-schema.ts
  packages/oas/src/lib/reducer.ts
  packages/oas/src/operation.ts
  packages/oas/src/operation/get-callback-examples.ts
  packages/oas/src/operation/get-parameters-as-json-schema.ts
  packages/oas/src/operation/get-requestbody-examples.ts
  packages/oas/src/operation/get-response-as-json-schema.ts
  packages/oas/src/operation/get-response-examples.ts
  packages/oas/src/samples/index.ts
  packages/oas/src/samples/utils.ts
  packages/oas/src/utils.ts
  packages/oas/test/__fixtures__/create-oas.ts
  packages/oas/test/__fixtures__/json-schema.ts
  packages/oas/test/__fixtures__/json-stringify-clean.js
  packages/oas/test/__fixtures__/json-stringify-clean.ts
  packages/oas/test/analyzer/index.test.ts
  packages/oas/test/analyzer/queries/openapi.test.ts
  packages/oas/test/analyzer/queries/readme.test.ts
  packages/oas/test/index.test.ts
  packages/oas/test/lib/find-schema-definition.test.ts
  packages/oas/test/lib/get-auth.test.ts
  packages/oas/test/lib/get-user-variable.test.ts
  packages/oas/test/lib/matches-mimetype.test.ts
  packages/oas/test/lib/openapi-to-json-schema.test.ts
  packages/oas/test/lib/openapi-to-json-schema/default.test.ts
  packages/oas/test/lib/openapi-to-json-schema/required.test.ts
  packages/oas/test/lib/reducer.test.ts
  packages/oas/test/operation.test.ts
  packages/oas/test/operation/get-callback-examples.test.ts
  packages/oas/test/operation/get-parameters-as-json-schema.test.ts
  packages/oas/test/operation/get-requestbody-examples.test.ts
  packages/oas/test/operation/get-response-as-json-schema.test.ts
  packages/oas/test/operation/get-response-examples.test.ts
  packages/oas/test/samples/index.test.ts
  packages/oas/test/ts-quirks.test.js
  packages/oas/test/utils.test.ts
  packages/oas/tsup.config.ts
Labels: refactor

#816 fix(oas): slightly refactoring how our utilities are exported
  packages/oas-to-har/src/index.ts
  packages/oas/src/index.ts
  packages/oas/src/operation.ts
  packages/oas/src/utils.ts
  packages/oas/test/index.test.ts
  packages/oas/test/utils.test.ts
Labels: refactor

#817 refactor: random config file cleanup
  .github/workflows/ci.yml
  .prettierignore
  package.json
  packages/oas-extensions/.eslintignore
  packages/oas-extensions/.npmignore
  packages/oas-extensions/package.json
  packages/oas-normalize/.eslintignore
  packages/oas-normalize/.npmignore
  packages/oas-normalize/package.json
  packages/oas-to-har/.eslintignore
  packages/oas-to-har/.npmignore
  packages/oas-to-har/package.json
  packages/oas/.eslintignore
  packages/oas/.npmignore
  packages/oas/package.json
Labels: refactor

#818 chore(deps): running `npm audit fix`
  package-lock.json
Labels: dependencies

#819 fix(oas-extensions): moving `oas` from being a peer to a hard dep
  package-lock.json
  packages/oas-extensions/package.json
Labels: bug

#821 chore(deps): bumping `remove-undefined-objects`
  package-lock.json
  packages/oas-to-har/package.json
  packages/oas/package.json
Labels: dependencies

#822 feat(oas-to-snippet): migrating `oas-to-snippet` into this repo
  package-lock.json
  packages/oas-to-snippet/LICENSE
  packages/oas-to-snippet/README.md
  packages/oas-to-snippet/bin/generate-target-markdown-table.js
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/index.ts
  packages/oas-to-snippet/src/lib/utils.ts
  packages/oas-to-snippet/src/supportedLanguages.ts
  packages/oas-to-snippet/src/types.ts
  packages/oas-to-snippet/test/.eslintrc
  packages/oas-to-snippet/test/__datasets__/owlbert-shrub.dataurl.json
  packages/oas-to-snippet/test/__datasets__/owlbert-shrub.png
  packages/oas-to-snippet/test/__datasets__/owlbert.dataurl.json
  packages/oas-to-snippet/test/__datasets__/owlbert.png
  packages/oas-to-snippet/test/__datasets__/query-encoded.har.json
  packages/oas-to-snippet/test/__datasets__/quirks/multipart-oneOf-requestbody.json
  packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
  packages/oas-to-snippet/test/index.test.ts
  packages/oas-to-snippet/test/lib/utils.test.ts
  packages/oas-to-snippet/test/tsconfig.json
  packages/oas-to-snippet/tsconfig.json
  packages/oas-to-snippet/tsup.config.ts
Labels: enhancement

#823 feat(oas-to-har): reducing the `lodash` footprint
  package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.ts
  packages/oas-to-har/src/lib/utils.ts
Labels: refactor

#826 feat(oas): refactoring `oas-extensions` completely into `oas` core
  package-lock.json
  packages/oas-extensions/.eslintrc
  packages/oas-extensions/LICENSE
  packages/oas-extensions/README.md
  packages/oas-extensions/package.json
  packages/oas-extensions/src/index.ts
  packages/oas-extensions/test/.eslintrc
  packages/oas-extensions/test/index.test.ts
  packages/oas-extensions/test/tsconfig.json
  packages/oas-extensions/tsconfig.json
  packages/oas-extensions/tsup.config.ts
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.ts
  packages/oas-to-har/test/index.test.ts
  packages/oas-to-har/test/requestBody.test.ts
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/test/index.test.ts
  packages/oas/README.md
  packages/oas/package.json
  packages/oas/src/extensions.ts
  packages/oas/src/index.ts
  packages/oas/src/operation/get-parameters-as-json-schema.ts
  packages/oas/test/extensions.test.ts
  packages/oas/test/index.test.ts
  packages/oas/test/operation/get-parameters-as-json-schema.test.ts
  packages/oas/tsup.config.ts
Labels: enhancement, refactor
