Repository readmeio/oas, pull requests merged in 2023-09, with the labels that each got.

#793 feat: added support for cjs and esm
  package-lock.json
  package.json
  tsconfig.json
  tsup.config.ts
Labels: enhancement

#795 fix: only add number bounds to number types
  __tests__/lib/openapi-to-json-schema.test.ts
  src/lib/openapi-to-json-schema.ts
Labels: bug

#796 fix: get exports working in TS `nodeNext`
  package.json
Labels: bug

#798 fix(tsup): drop `treeshaking` flag, lint fixes
  __tests__/ts-quirks.test.js
  package.json
  tsup.config.ts
Labels: bug

#799 fix: get default export working in both ESM/CJS
  __tests__/index.test.ts
  __tests__/operation.test.ts
  src/index.ts
  src/operation.ts
  src/utils.ts
Labels: bug

#801 fix: get default export working in both ESM/CJS (again)
  __tests__/index.test.ts
  __tests__/operation.test.ts
  src/index.ts
  src/operation.ts
  src/utils.ts
Labels: bug

#802 chore(deps): bump
  package-lock.json
  package.json
  src/lib/reducer.ts
Labels: dependencies

#803 feat(breaking): drop node 16 support
  .github/workflows/ci.yml
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement
