Repository readmeio/oas, pull requests merged in 2024-04, with the labels that each got.

#852 docs: deprecate `operation.getExtension()`, typing improvements
  packages/oas-normalize/src/index.ts
  packages/oas/README.md
  packages/oas/src/operation/index.ts
Labels: documentation

#853 chore(deps): bumping all out of date deps
  package-lock.json
  package.json
  packages/oas-normalize/package.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
  packages/oas/package.json
Labels: dependencies

#855 feat(snippet): making the library synchronous again
  package-lock.json
  packages/oas-to-snippet/README.md
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/index.ts
  packages/oas-to-snippet/test/index.test.ts
Labels: enhancement, refactor

#856 feat(oas-to-snippet): exporting the `HarRequest` type for use
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/index.ts
  packages/oas-to-snippet/src/types.ts
  packages/oas-to-snippet/tsup.config.ts
Labels: enhancement

#857 refactor: strict mode, more helpful return types
  packages/oas-normalize/src/index.ts
  packages/oas-normalize/src/lib/utils.ts
  packages/oas-normalize/tsconfig.json
  packages/oas-to-har/src/index.ts
  packages/oas-to-har/src/lib/configure-security.ts
  packages/oas-to-har/src/lib/style-formatting/index.ts
  packages/oas-to-har/src/lib/style-formatting/style-serializer.ts
  packages/oas-to-har/src/lib/utils.ts
  packages/oas-to-har/tsconfig.json
  packages/oas-to-snippet/src/index.ts
  packages/oas-to-snippet/src/languages.ts
  packages/oas-to-snippet/tsconfig.json
Labels: refactor, documentation

#858 fix(oas-to-har): use CJS lodash instead
  package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.ts
  packages/oas-to-har/src/lib/utils.ts
Labels: bug

#859 fix: no more lodash, bump types, type cleanup/re-export
  package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.ts
  packages/oas-to-har/src/lib/lodash.ts
  packages/oas-to-har/src/lib/utils.ts
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/index.ts
  packages/oas-to-snippet/src/types.ts
Labels: bug, dependencies, refactor

#860 feat(oas-to-snippet): surface installation instructions with snippets
  packages/oas-to-snippet/src/index.ts
  packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
  packages/oas-to-snippet/test/index.test.ts
  packages/oas-to-snippet/test/languages.test.ts
Labels: enhancement

#861 fix(oas-to-snippet): use correct val for registry identifier
  packages/oas-to-snippet/src/index.ts
  packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
Labels: bug

#862 fix(oas-normalize): dont attempt to upconvert an OpenAPI definition
  packages/oas-normalize/src/index.ts
  packages/oas-normalize/test/index.test.ts
  packages/oas-to-har/test/lib/style-formatting/multipart-form-data.test.ts
Labels: bug

#864 feat: support examples from openapi 3.1
  packages/oas/src/samples/index.ts
  packages/oas/test/samples/index.test.ts
Labels: enhancement

#867 fix(oas-to-snippet): bumping httpsnippet for swift multipart fixes
  package-lock.json
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
Labels: enhancement, dependencies

#866 feat(oas): example groups accessor
  package-lock.json
  packages/oas-to-har/src/lib/types.ts
  packages/oas/README.md
  packages/oas/src/extensions.ts
  packages/oas/src/operation/index.ts
  packages/oas/src/operation/lib/get-example-groups.ts
  packages/oas/src/operation/lib/get-requestbody-examples.ts
  packages/oas/src/types.ts
  packages/oas/test/__snapshots__/index.test.ts.snap
  packages/oas/test/operation/lib/__snapshots__/get-example-groups.test.ts.snap
  packages/oas/test/operation/lib/get-example-groups.test.ts
Labels: enhancement

#851 fix(oas): numerous tweaks to our camelCase `operationId` generation
  packages/oas/src/operation/index.ts
  packages/oas/test/operation/index.test.ts
Labels: enhancement

#869 revert: "fix(oas): numerous tweaks to our camelCase `operationId` generation"
  packages/oas/src/operation/index.ts
  packages/oas/test/operation/index.test.ts
Labels: bug

#870 fix: make `RequestBodyExamples` type stricter
  packages/oas/src/operation/lib/get-requestbody-examples.ts
Labels: bug
