Repository readmeio/oas, pull requests merged in 2024-05, with the labels that each got.

#873 fix(oas/exampleGroups): properly set name for code samples
  package-lock.json
  packages/oas/src/operation/lib/get-example-groups.ts
  packages/oas/test/operation/lib/__snapshots__/get-example-groups.test.ts.snap
Labels: bug, dependencies

#875 ci: simplify vitest setup
  packages/oas-normalize/test/index.chdir.test.ts
  packages/oas-normalize/test/index.test.ts
  packages/oas-normalize/vitest.config.chdir.ts
  packages/oas-normalize/vitest.config.ts
  packages/oas-normalize/vitest.workspace.ts
  vitest.workspace.ts
Labels: refactor

#874 fix(exampleGroups): add code sample index
  packages/oas/src/operation/lib/get-example-groups.ts
  packages/oas/test/operation/lib/__snapshots__/get-example-groups.test.ts.snap
Labels: enhancement

#876 fix(oas): update memoizee(vulnerability)
  package-lock.json
  packages/oas/package.json
Labels: dependencies

#877 chore(deps): bumping openapi-parser
  package-lock.json
  packages/oas-normalize/package.json
  packages/oas/package.json
Labels: dependencies
