Repository readmeio/oas, pull requests merged in 2024-09, with the labels that each got.

#896 feat(oas): type improvements for `oas.splitUrl()`
  packages/oas/src/index.ts
  packages/oas/test/index.test.ts
Labels: enhancement, documentation

#897 refactor(oas): export and reuse `Variables` type
  packages/oas/src/index.ts
  packages/oas/src/types.ts
Labels: bug, refactor

#894 feat(oas/extensions): oauth configuration options
  packages/oas/src/extensions.ts
  packages/oas/src/index.ts
  packages/oas/src/operation/lib/get-example-groups.ts
  packages/oas/test/extensions.test.ts
Labels: enhancement

#899 feat(snippet): upgrading `httsnippet` for some JS/Node modernizations
  package-lock.json
  packages/oas-to-snippet/README.md
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/languages.ts
  packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
  packages/oas-to-snippet/test/__snapshots__/languages.test.ts.snap
  packages/oas-to-snippet/test/index.test.ts
Labels: enhancement

#900 docs(oas): writing up docs on `oas/reducer` and `oas/analyzer`
  packages/oas/README.md
  packages/oas/src/reducer/index.ts
Labels: documentation

#902 chore(deps): upgrading `path-to-regexp`
  package-lock.json
  packages/oas-normalize/package.json
  packages/oas-normalize/test/index.test.ts
  packages/oas/package.json
  packages/oas/src/index.ts
  packages/oas/test/index.test.ts
Labels: enhancement, dependencies

#904 fix: add empty `value` check in getRequestBodyExamples()
  packages/oas/src/operation/index.ts
  packages/oas/test/operation/lib/get-requestbody-examples.test.ts
Labels: bug
