Repository readmeio/oas, pull requests merged in 2025-06, with the labels that each got.

#979 refactor: removing wildcard imports
  package-lock.json
  package.json
  packages/oas-normalize/src/index.ts
  packages/oas/src/analyzer/index.ts
  packages/oas/src/index.ts
  packages/oas/src/lib/get-auth.ts
  packages/oas/src/lib/get-user-variable.ts
  packages/oas/src/lib/openapi-to-json-schema.ts
  packages/oas/src/operation/index.ts
  packages/oas/src/operation/lib/dedupe-common-parameters.ts
  packages/oas/src/operation/lib/get-callback-examples.ts
  packages/oas/src/operation/lib/get-example-groups.ts
  packages/oas/src/operation/lib/get-mediatype-examples.ts
  packages/oas/src/operation/lib/get-requestbody-examples.ts
  packages/oas/src/operation/lib/get-response-examples.ts
  packages/oas/src/samples/index.ts
  packages/oas/src/samples/utils.ts
  packages/oas/test/.eslintrc
  packages/oas/test/__fixtures__/create-oas.ts
  packages/oas/test/analyzer/queries/openapi.test.ts
  packages/oas/test/analyzer/queries/readme.test.ts
  packages/oas/test/extensions.test.ts
  packages/oas/test/index.test.ts
  packages/oas/test/operation/index.test.ts
  packages/oas/test/operation/lib/get-response-examples.test.ts
  packages/oas/test/samples/index.test.ts
Labels: refactor

#983 chore(deps): upgrading out of date dependencies
  package-lock.json
  package.json
  packages/har-examples/package.json
  packages/http-status-codes/package.json
  packages/jest-expect-har/package.json
  packages/jest-expect-openapi/package.json
  packages/oas-examples/package.json
  packages/oas-normalize/package.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package.json
  packages/oas/package.json
  packages/parser/package.json
  vitest.config.mts
Labels: dependencies

#982 feat(oas): add support for displaying definition size in analyzer
  packages/oas/README.md
  packages/oas/src/analyzer/index.ts
  packages/oas/src/analyzer/queries/openapi.ts
  packages/oas/src/analyzer/types.ts
  packages/oas/test/analyzer/__snapshots__/index.test.ts.snap
  packages/oas/test/analyzer/queries/openapi.test.ts
Labels: enhancement
