Repository readmeio/oas, pull requests merged in 2025-03, with the labels that each got.

#947 fix(snippet): hide install instructions for fetch fallback
  packages/oas-to-snippet/src/index.ts
  packages/oas-to-snippet/test/index.test.ts
Labels: bug

#943 feat(parser): new system for downgrading some OpenAPI errors to warnings
  package-lock.json
  packages/oas-normalize/README.md
  packages/oas-normalize/package.json
  packages/oas-normalize/src/index.ts
  packages/oas-normalize/src/lib/errors.ts
  packages/oas-normalize/src/lib/utils.ts
  packages/oas-normalize/test/__snapshots__/index.test.ts.snap
  packages/oas-normalize/test/index.test.ts
  packages/oas-normalize/tsup.config.ts
  packages/oas/test/operation/index.test.ts
  packages/oas/test/operation/lib/get-response-as-json-schema.test.ts
  packages/parser/README.md
  packages/parser/bin/refresh-real-world-apis
  packages/parser/package.json
  packages/parser/src/errors.ts
  packages/parser/src/index.ts
  packages/parser/src/lib/reduceAjvErrors.ts
  packages/parser/src/types.ts
  packages/parser/src/util.ts
  packages/parser/src/validators/schema.ts
  packages/parser/src/validators/spec.ts
  packages/parser/src/validators/spec/index.ts
  packages/parser/src/validators/spec/openapi.ts
  packages/parser/src/validators/spec/swagger.ts
  packages/parser/test/.eslintrc
  packages/parser/test/specs/better-errors/better-errors.test.ts
  packages/parser/test/specs/circular/circular.test.ts
  packages/parser/test/specs/colorize-errors-option/colorize-errors-option.test.ts
  packages/parser/test/specs/compile-errors/compile-errors.test.ts
  packages/parser/test/specs/compile-errors/invalid-with-errors-and-warnings.yaml
  packages/parser/test/specs/compile-errors/invalid-with-multiple-errors.yaml
  packages/parser/test/specs/deep-circular/deep-circular.test.ts
  packages/parser/test/specs/invalid/__snapshots__/invalid.test.ts.snap
  packages/parser/test/specs/invalid/invalid.test.ts
  packages/parser/test/specs/large-file-memory-leak/large-file-memory-leak.test.ts
  packages/parser/test/specs/real-world/known-errors.ts
  packages/parser/test/specs/real-world/real-world-apis.json
  packages/parser/test/specs/real-world/real-world.test.ts
  packages/parser/test/specs/unknown/unknown.test.ts
  packages/parser/test/specs/validate-schema/__snapshots__/validate-schema.test.ts.snap
  packages/parser/test/specs/validate-schema/validate-schema.test.ts
  packages/parser/test/specs/validate-spec/__snapshots__/validate-spec.test.ts.snap
  packages/parser/test/specs/validate-spec/invalid/3.x/array-body-no-items.yaml
  packages/parser/test/specs/validate-spec/validate-spec.test.ts
  packages/parser/test/vitest.matchers.ts
Labels: enhancement

#948 ci: running `attw` as part of our ci processes
  .github/workflows/ci.yml
  package-lock.json
  package.json
  packages/oas-normalize/package.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package.json
  packages/oas/package.json
  packages/parser/package.json
  packages/postman-types/package.json
Labels: enhancement

#949 fix: getting `jest-expect-har` and `jest-expect-openapi` functional
  knip.ts
  package-lock.json
  package.json
  packages/jest-expect-har/.eslintignore
  packages/jest-expect-har/.eslintrc
  packages/jest-expect-har/.github/dependabot.yml
  packages/jest-expect-har/.github/workflows/ci.yml
  packages/jest-expect-har/.github/workflows/codeql-analysis.yml
  packages/jest-expect-har/.gitignore
  packages/jest-expect-har/.npmrc
  packages/jest-expect-har/.prettierignore
  packages/jest-expect-har/LICENSE
  packages/jest-expect-har/__tests__/vitest.test.ts
  packages/jest-expect-har/jest.config.js
  packages/jest-expect-har/package-lock.json
  packages/jest-expect-har/package.json
  packages/jest-expect-har/test/.eslintrc
  packages/jest-expect-har/test/__fixtures__/har.valid.json
  packages/jest-expect-har/test/index.test.ts
  packages/jest-expect-har/test/tsconfig.json
  packages/jest-expect-har/test/tsconfig.vitest.json
  packages/jest-expect-har/vitest.config.mts
  packages/jest-expect-openapi/.eslintignore
  packages/jest-expect-openapi/.eslintrc
  packages/jest-expect-openapi/.github/dependabot.yml
  packages/jest-expect-openapi/.github/workflows/ci.yml
  packages/jest-expect-openapi/.github/workflows/codeql-analysis.yml
  packages/jest-expect-openapi/.gitignore
  packages/jest-expect-openapi/.npmrc
  packages/jest-expect-openapi/.prettierignore
  packages/jest-expect-openapi/jest.config.js
  packages/jest-expect-openapi/package-lock.json
  packages/jest-expect-openapi/package.json
  packages/jest-expect-openapi/src/index.ts
  packages/jest-expect-openapi/test/.eslintrc
  packages/jest-expect-openapi/test/__fixtures__/invalid-oas.json
  packages/jest-expect-openapi/test/__fixtures__/valid-oas.json
  packages/jest-expect-openapi/test/index.test.ts
  packages/jest-expect-openapi/test/tsconfig.json
  packages/jest-expect-openapi/test/tsconfig.vitest.json
  packages/jest-expect-openapi/vitest.config.mts
Labels: enhancement

#950 chore: getting the `oas-examples` package working again
  .github/workflows/sync.yml
  .github/workflows/validate.yml
  package-lock.json
  packages/jest-expect-har/README.md
  packages/jest-expect-openapi/README.md
  packages/oas-examples/.eslintignore
  packages/oas-examples/.github/dependabot.yml
  packages/oas-examples/.github/workflows/ci.yml
  packages/oas-examples/.gitignore
  packages/oas-examples/.npmrc
  packages/oas-examples/.prettierignore
  packages/oas-examples/LICENSE.md
  packages/oas-examples/README.md
  packages/oas-examples/__tests__/.eslintrc
  packages/oas-examples/__tests__/tsconfig.json
  packages/oas-examples/package-lock.json
  packages/oas-examples/package.json
  packages/oas-examples/test/index.test.ts
  packages/oas-examples/test/tsconfig.json
  packages/oas-normalize/package.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package.json
  packages/oas/package.json
Labels: enhancement

#951 chore: getting `har-examples` functional again
  package-lock.json
  packages/har-examples/.eslintignore
  packages/har-examples/.eslintrc
  packages/har-examples/.github/workflows/ci.yml
  packages/har-examples/.github/workflows/codeql-analysis.yml
  packages/har-examples/.gitignore
  packages/har-examples/.licenses/httpsnippet.md
  packages/har-examples/.npmignore
  packages/har-examples/.npmrc
  packages/har-examples/LICENSE
  packages/har-examples/README.md
  packages/har-examples/index.js
  packages/har-examples/package-lock.json
  packages/har-examples/package.json
  packages/har-examples/test/index.test.js
  packages/oas-to-snippet/package.json
Labels: bug

#952 feat(http-status-codes): making the library ESM w/ dual builds
  package-lock.json
  packages/http-status-codes/.eslintignore
  packages/http-status-codes/.eslintrc.json
  packages/http-status-codes/.github/workflows/ci.yml
  packages/http-status-codes/.github/workflows/codeql-analysis.yml
  packages/http-status-codes/.gitignore
  packages/http-status-codes/.npmignore
  packages/http-status-codes/.prettierignore
  packages/http-status-codes/LICENSE
  packages/http-status-codes/README.md
  packages/http-status-codes/package-lock.json
  packages/http-status-codes/package.json
  packages/http-status-codes/src/index.ts
  packages/http-status-codes/test/.eslintrc
  packages/http-status-codes/test/index.test.ts
  packages/http-status-codes/tsup.config.ts
Labels: enhancement

#953 feat: dropping support for node 18
  package-lock.json
  package.json
  packages/http-status-codes/package.json
  packages/jest-expect-har/package.json
  packages/jest-expect-openapi/package.json
  packages/oas-normalize/package.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package.json
  packages/oas/package.json
  packages/parser/package.json
  packages/postman-types/package.json
Labels: enhancement

#954 fix(parser): loading in `$RefParser` from the named export
  packages/parser/src/index.ts
  packages/parser/test/specs/oas-relative-servers/v3-relative-servers.test.ts
Labels: bug

#955 feat(oas-normalize): adding support for parser options on `.deref()`
  packages/oas-normalize/src/index.ts
  packages/oas-normalize/src/lib/types.ts
  packages/oas-normalize/test/index.test.ts
Labels: enhancement

#956 fix(oas): typings on `getResponseAsJSONSchema` are wrong
  packages/oas/src/operation/lib/get-response-as-json-schema.ts
Labels: bug

#958 feat(jest-expect-har): support for CJS and ESM builds
  packages/jest-expect-har/package.json
  packages/jest-expect-har/test/tsconfig.json
  packages/jest-expect-har/tsconfig.json
  packages/jest-expect-har/tsup.config.ts
Labels: enhancement

#959 feat(jest-expect-openapi): support for CJS and ESM builds
  packages/jest-expect-openapi/package.json
  packages/jest-expect-openapi/src/index.ts
  packages/jest-expect-openapi/test/index.test.ts
  packages/jest-expect-openapi/test/tsconfig.json
  packages/jest-expect-openapi/tsconfig.json
  packages/jest-expect-openapi/tsup.config.ts
Labels: enhancement

#961 chore(oas-to-snippet): mock out `httpsnippet-client-api` behaviors
  package-lock.json
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/test/__fixtures__/plugin.ts
  packages/oas-to-snippet/test/__fixtures__/pluginFailure.ts
  packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
  packages/oas-to-snippet/test/index.test.ts
  packages/oas-to-snippet/test/languages.test.ts
Labels: refactor

#962 feat(oas-normalize): exporting some more types from our parser
  packages/oas-normalize/src/lib/types.ts
Labels: enhancement

#963 chore: `npm up`, enable `erasableSyntaxOnly`
  package-lock.json
  tsconfig.base.json
Labels: enhancement, dependencies
