Repository readmeio/oas, pull requests merged in 2025-02, with the labels that each got.

#931 fix: pointing our packages to the newly migrated parser library
  package-lock.json
  packages/oas-normalize/package.json
  packages/oas-normalize/src/index.ts
  packages/oas-normalize/test/__snapshots__/index.test.ts.snap
  packages/oas/package.json
  packages/parser/package-lock.json
  packages/parser/package.json
Labels: bug

#933 refactor: modern TS touchups
  packages/oas-normalize/src/index.ts
  packages/oas-normalize/src/lib/utils.ts
  packages/oas-to-har/src/index.ts
  packages/oas-to-har/src/lib/configure-security.ts
  packages/oas-to-har/src/lib/style-formatting/index.ts
  packages/oas-to-har/src/lib/style-formatting/style-serializer.ts
  packages/oas-to-har/src/lib/types.ts
  packages/oas-to-har/src/lib/utils.ts
  packages/oas-to-snippet/src/languages.ts
  packages/oas/src/analyzer/queries/openapi.ts
  packages/oas/src/analyzer/queries/readme.ts
  packages/oas/src/extensions.ts
  packages/oas/src/index.ts
  packages/oas/src/lib/find-schema-definition.ts
  packages/oas/src/lib/get-auth.ts
  packages/oas/src/lib/get-user-variable.ts
  packages/oas/src/lib/helpers.ts
  packages/oas/src/operation/index.ts
  packages/oas/src/operation/lib/dedupe-common-parameters.ts
  packages/oas/src/operation/lib/get-callback-examples.ts
  packages/oas/src/operation/lib/get-mediatype-examples.ts
  packages/oas/src/operation/lib/get-parameters-as-json-schema.ts
  packages/oas/src/operation/lib/get-requestbody-examples.ts
  packages/oas/src/operation/lib/get-response-as-json-schema.ts
  packages/oas/src/reducer/index.ts
  packages/oas/src/samples/index.ts
  packages/oas/src/samples/utils.ts
  packages/oas/src/types.ts
  packages/oas/src/utils.ts
  packages/oas/test/__snapshots__/index.test.ts.snap
  packages/oas/test/ts-quirks.test.ts
  packages/parser/src/index.ts
  packages/parser/src/lib/index.ts
  packages/parser/src/lib/reduceAjvErrors.ts
  packages/parser/src/options.ts
  packages/parser/src/util.ts
  packages/parser/src/validators/schema.ts
  packages/parser/src/validators/spec/openapi.ts
  packages/parser/src/validators/spec/swagger.ts
  tsconfig.base.json
Labels: refactor

#936 feat(parser): rewriting the parser (again) to make it fully static
  package-lock.json
  packages/oas-normalize/src/index.ts
  packages/oas-normalize/test/__snapshots__/index.test.ts.snap
  packages/oas-normalize/test/index.test.ts
  packages/oas/test/operation/index.test.ts
  packages/oas/test/operation/lib/get-response-as-json-schema.test.ts
  packages/parser/.eslintrc
  packages/parser/README.md
  packages/parser/package.json
  packages/parser/src/index.ts
  packages/parser/src/lib/index.ts
  packages/parser/src/options.ts
  packages/parser/src/repair.ts
  packages/parser/src/types.ts
  packages/parser/src/util.ts
  packages/parser/src/validators/schema.ts
  packages/parser/src/validators/spec/openapi.ts
  packages/parser/test/specs/awaited-behavior/awaited-behavior-error.yaml
  packages/parser/test/specs/awaited-behavior/awaited-behavior.test.ts
  packages/parser/test/specs/awaited-behavior/awaited-behavior.yaml
  packages/parser/test/specs/awaited-behavior/bundled.ts
  packages/parser/test/specs/awaited-behavior/dereferenced.ts
  packages/parser/test/specs/awaited-behavior/parsed.ts
  packages/parser/test/specs/better-errors/better-errors.test.ts
  packages/parser/test/specs/circular/circular.test.ts
  packages/parser/test/specs/colorize-errors-option/colorize-errors-option.test.ts
  packages/parser/test/specs/deep-circular/deep-circular.test.ts
  packages/parser/test/specs/invalid/__snapshots__/invalid.test.ts.snap
  packages/parser/test/specs/invalid/invalid.test.ts
  packages/parser/test/specs/invalid/no-paths-or-webhooks.yaml
  packages/parser/test/specs/large-file-memory-leak/large-file-memory-leak.test.ts
  packages/parser/test/specs/oas-relative-servers/v3-relative-servers.test.ts
  packages/parser/test/specs/object-source/object-source.test.ts
  packages/parser/test/specs/real-world/real-world.test.ts
  packages/parser/test/specs/unknown/unknown.test.ts
  packages/parser/test/specs/validate-schema/validate-schema.test.ts
  packages/parser/test/specs/validate-spec/validate-spec.test.ts
  packages/parser/test/tsconfig.json
  packages/parser/test/utils.ts
  packages/parser/test/utils/helper.ts
  packages/parser/test/utils/path.ts
Labels: bug, enhancement, refactor

#937 feat(oas): replacing `json-schema-ref-parser` with our new parser library
  package-lock.json
  package.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package.json
  packages/oas/package.json
  packages/oas/src/index.ts
  packages/oas/test/analyzer/queries/openapi.test.ts
  packages/oas/test/index.test.ts
  packages/parser/.eslintrc
  packages/parser/package.json
  packages/parser/src/index.ts
  packages/parser/src/lib/reduceAjvErrors.ts
  packages/parser/src/repair.ts
  packages/parser/src/types.ts
  packages/parser/src/util.ts
  packages/parser/src/validators/schema.ts
Labels: enhancement

#940 refactor: swapping out `type-fest` for a pure TS type
  package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/lib/style-formatting/style-serializer.ts
Labels: refactor

#941 ci: enabling knip on the repository
  knip.ts
  package-lock.json
  package.json
  packages/oas-to-har/src/lib/style-formatting/style-serializer.ts
  packages/parser/package.json
  packages/parser/src/validators/schema.ts
  packages/parser/src/validators/spec.ts
Labels: enhancement

#942 fix(security): swapping out `jsonpath-plus` for `jsonpath` in v20
  __tests__/analyzer/__snapshots__/index.test.ts.snap
  __tests__/analyzer/queries/openapi.test.ts
  __tests__/analyzer/queries/readme.test.ts
  package-lock.json
  package.json
  src/analyzer/queries/openapi.ts
  src/analyzer/queries/readme.ts
  src/analyzer/util.ts
Labels: security

#944 ci: more knip cleanup
  knip.ts
  package-lock.json
  package.json
  packages/oas-normalize/package.json
  packages/oas-normalize/tsup.config.ts
  packages/oas-to-har/package.json
  packages/oas-to-har/tsup.config.ts
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/tsup.config.ts
  packages/oas/package.json
  packages/oas/tsup.config.ts
  packages/parser/package.json
  packages/parser/tsup.config.ts
  packages/postman-types/package.json
  packages/postman-types/tsup.config.ts
  tsup.config.ts
Labels: enhancement
